# Import NumPy Library 

In [3]:
import numpy as np 

In [8]:
a = np.array([1,2,3])
print (a)

[1 2 3]


In [15]:
# Create Matrix 
b = np.array([[1,2,],[4,5,6]]) #Create a 2 by 3 matrix 
print (b)

[[1 2 3]
 [4 5 6]]


In [35]:
# Get Dimension 
a.ndim

2

In [33]:
#Get Shape 
print(a.shape)
print(b.shape) #return the row and column count of b 


(3,)
(2, 3)


In [36]:
# Get Datatype 
a.dtype 

dtype('int64')

In [46]:
# Specify Datatypes when generating Matirx: 
c = np.array([3,4,5], dtype='int16')
print(c)          # Print c
print(c.dtype)    # Return the Data type of the elements
print(c.itemsize) # Return each individual item's size 
print(c.size)     # Return element count | Return # of element in matrix 
print(c.nbytes)   # Return the total number of bytes in this array 

[3 4 5]
int16
2
6


# Accessing/ Changing specific Elements, rows, columns, etc 